version: '3'

services:

  frontend:
    labels:
      shipyard.route: '/'
    build:
      context: 'frontend'
    ports:
      - '3000:3000'
    env_file:
      - frontend/frontend.env
    volumes:
      - './frontend/src:/app/src'

  postgres:
    image: 'postgres:9.6-alpine'
    restart: always
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    environment:
      - DEV: ${DEV}
      - OMAR: ${OMAR}
      - DEV2: ${DEV2}
      - POSTGRES_DB=app
      - POSTGRES_USER=obscure-user
      - POSTGRES_PASSWORD=obscure-password
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - '5432'

  backend:
    labels:
      shipyard.before: 'npx sequelize-cli db:migrate'
      shipyard.route: '/api'
    build:
      context: 'backend'
    environment:
      DB_USER: 'obscure-user'
      DB_PASSWORD: 'obscure-password'
      DB_NAME: 'app'
      DB_HOST: 'postgres'
      DB_PORT: '5432'
      LOCALSTACK_HOST: 'localstack'
    depends_on:
      - 'postgres'
    ports:
      - '8080:8080'
    volumes:
      - './backend/src:/app/src'

  localstack:
    image: 'localstack/localstack'
    environment:
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - 'localstack:/tmp/localstack'
    ports:
      - '4566'

volumes:
  postgres:
  localstack:
